[tool.pytest.ini_options]
minversion = "6.0"
xfail_strict=true
addopts = [
    "-vv",
    "--color=yes",
]

[tool.black]
line-length = 100

[tool.coverage.report]
exclude_lines = [
  "pragma: nocover",
  "raise NotImplementedError",
  "if TYPE_CHECKING:",
]

[tool.nbqa.mutate]
isort = 1
black = 1
pyupgrade = 1
